package views;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;


public class LocalidadesVista extends javax.swing.JDialog {

    public final static int PARAMETER_IDPROVINCE = 1;
    public final static int PARAMETER_POSTAL_CODE = 2;
    private boolean okButton;
    private LocalidadesVista myModal;
    
    public LocalidadesVista(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        okButton = false;
        this.myModal = this;
        initComponents();
        
        this.jButtonContinuar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
               myModal.setVisible(false);
               okButton = true;
               myModal.dispose();
            }
        });
        
        this.setVisible(true);
    }

    public boolean isOkButton() {
        return okButton;
    }
    
    public LocalidadesVista(java.awt.Frame parent, boolean modal, String parameter, int typeParameter) {
        super(parent, modal);
        
        okButton = false;
        this.myModal = this;
        initComponents();
        
        this.jButtonContinuar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
               myModal.setVisible(false);
               okButton = true;
               myModal.dispose();
            }
        });
        
        switch (typeParameter) {
            case PARAMETER_IDPROVINCE:
                this.jFormattedTextFieldIdProvincia.setText(parameter);
                break;
            case PARAMETER_POSTAL_CODE:
                this.jFormattedTextFieldIdProvincia.setText(parameter.substring(0, 2));
                this.jFormattedTextFieldCodigoPostal.setText(parameter.substring(2, 5));
                this.jFormattedTextFieldCodigoPostal.setEditable(false);
                break;
        }
        this.setVisible(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelCodigoPostal = new javax.swing.JLabel();
        jFormattedTextFieldIdProvincia = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCodigoPostal = new javax.swing.JFormattedTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextField1Nombre = new javax.swing.JTextField();
        jLabelPoblacion = new javax.swing.JLabel();
        jFormattedTextFieldPoblacion = new javax.swing.JFormattedTextField();
        jButtonContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTitulo.setText("Inserte los datos de la localidad");

        jLabelCodigoPostal.setText("Código postal");

        jFormattedTextFieldIdProvincia.setEditable(false);

        jLabelNombre.setText("Nombre");

        jTextField1Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1NombreActionPerformed(evt);
            }
        });

        jLabelPoblacion.setText("Población");

        jFormattedTextFieldPoblacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldPoblacionActionPerformed(evt);
            }
        });

        jButtonContinuar.setText("Continuar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelPoblacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                .addComponent(jLabelNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabelCodigoPostal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jFormattedTextFieldIdProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldCodigoPostal))
                            .addComponent(jFormattedTextFieldPoblacion)
                            .addComponent(jTextField1Nombre)
                            .addComponent(jButtonContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextFieldIdProvincia)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFormattedTextFieldCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCodigoPostal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldPoblacion, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabelPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1NombreActionPerformed

    private void jFormattedTextFieldPoblacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPoblacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldPoblacionActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonContinuar;
    private javax.swing.JFormattedTextField jFormattedTextFieldCodigoPostal;
    private javax.swing.JFormattedTextField jFormattedTextFieldIdProvincia;
    private javax.swing.JFormattedTextField jFormattedTextFieldPoblacion;
    private javax.swing.JLabel jLabelCodigoPostal;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPoblacion;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextField1Nombre;
    // End of variables declaration//GEN-END:variables

    public JButton getjButtonContinuar() {
        return jButtonContinuar;
    }

    public void setjButtonContinuar(JButton jButtonContinuar) {
        this.jButtonContinuar = jButtonContinuar;
    }

    public JFormattedTextField getjFormattedTextFieldCodigoPostal() {
        return jFormattedTextFieldCodigoPostal;
    }

    public void setjFormattedTextFieldCodigoPostal(JFormattedTextField jFormattedTextFieldCodigoPostal) {
        this.jFormattedTextFieldCodigoPostal = jFormattedTextFieldCodigoPostal;
    }

    public JFormattedTextField getjFormattedTextFieldIdProvincia() {
        return jFormattedTextFieldIdProvincia;
    }

    public void setjFormattedTextFieldIdProvincia(JFormattedTextField jFormattedTextFieldIdProvincia) {
        this.jFormattedTextFieldIdProvincia = jFormattedTextFieldIdProvincia;
    }

    public JFormattedTextField getjFormattedTextFieldPoblacion() {
        return jFormattedTextFieldPoblacion;
    }

    public void setjFormattedTextFieldPoblacion(JFormattedTextField jFormattedTextFieldPoblacion) {
        this.jFormattedTextFieldPoblacion = jFormattedTextFieldPoblacion;
    }

    public JTextField getjTextField1Nombre() {
        return jTextField1Nombre;
    }

    public void setjTextField1Nombre(JTextField jTextField1Nombre) {
        this.jTextField1Nombre = jTextField1Nombre;
    }

    
}
